// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: pkg/nettest/net_test.proto

package nettest

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Start struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Length int32 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
}

func (x *Start) Reset() {
	*x = Start{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_nettest_net_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Start) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Start) ProtoMessage() {}

func (x *Start) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_nettest_net_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Start.ProtoReflect.Descriptor instead.
func (*Start) Descriptor() ([]byte, []int) {
	return file_pkg_nettest_net_test_proto_rawDescGZIP(), []int{0}
}

func (x *Start) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Start) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type Number struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *Number) Reset() {
	*x = Number{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_nettest_net_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Number) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Number) ProtoMessage() {}

func (x *Number) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_nettest_net_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Number.ProtoReflect.Descriptor instead.
func (*Number) Descriptor() ([]byte, []int) {
	return file_pkg_nettest_net_test_proto_rawDescGZIP(), []int{1}
}

func (x *Number) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

var File_pkg_nettest_net_test_proto protoreflect.FileDescriptor

var file_pkg_nettest_net_test_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x6b, 0x67, 0x2f, 0x6e, 0x65, 0x74, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x6e, 0x65,
	0x74, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6e, 0x65,
	0x74, 0x74, 0x65, 0x73, 0x74, 0x22, 0x37, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x22, 0x20,
	0x0a, 0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x32, 0x3d, 0x0a, 0x07, 0x4e, 0x65, 0x74, 0x54, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x0b, 0x4c,
	0x69, 0x73, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x0e, 0x2e, 0x6e, 0x65, 0x74,
	0x74, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x1a, 0x0f, 0x2e, 0x6e, 0x65, 0x74,
	0x74, 0x65, 0x73, 0x74, 0x2e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x00, 0x30, 0x01, 0x42,
	0x25, 0x5a, 0x23, 0x6a, 0x69, 0x75, 0x63, 0x68, 0x65, 0x6e, 0x31, 0x39, 0x38, 0x36, 0x2f, 0x68,
	0x65, 0x6c, 0x6c, 0x6f, 0x2d, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6e,
	0x65, 0x74, 0x74, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_nettest_net_test_proto_rawDescOnce sync.Once
	file_pkg_nettest_net_test_proto_rawDescData = file_pkg_nettest_net_test_proto_rawDesc
)

func file_pkg_nettest_net_test_proto_rawDescGZIP() []byte {
	file_pkg_nettest_net_test_proto_rawDescOnce.Do(func() {
		file_pkg_nettest_net_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_nettest_net_test_proto_rawDescData)
	})
	return file_pkg_nettest_net_test_proto_rawDescData
}

var file_pkg_nettest_net_test_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_nettest_net_test_proto_goTypes = []interface{}{
	(*Start)(nil),  // 0: nettest.Start
	(*Number)(nil), // 1: nettest.Number
}
var file_pkg_nettest_net_test_proto_depIdxs = []int32{
	0, // 0: nettest.NetTest.ListNumbers:input_type -> nettest.Start
	1, // 1: nettest.NetTest.ListNumbers:output_type -> nettest.Number
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_nettest_net_test_proto_init() }
func file_pkg_nettest_net_test_proto_init() {
	if File_pkg_nettest_net_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_nettest_net_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Start); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_nettest_net_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Number); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_nettest_net_test_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_nettest_net_test_proto_goTypes,
		DependencyIndexes: file_pkg_nettest_net_test_proto_depIdxs,
		MessageInfos:      file_pkg_nettest_net_test_proto_msgTypes,
	}.Build()
	File_pkg_nettest_net_test_proto = out.File
	file_pkg_nettest_net_test_proto_rawDesc = nil
	file_pkg_nettest_net_test_proto_goTypes = nil
	file_pkg_nettest_net_test_proto_depIdxs = nil
}
